### ISSUE TITLE
As you swipe back on a cell, its layout gets corrupted.

### ISSUE THREAD

**Issue by devValley** [cuzv/RRSwipeCell#1]
As you swipe back on a cell, its content layout gets corrupted. Please see the attached screenshot which demonstrates the issue.

<img width="487" alt="screen shot 2017-08-21 at 12 37 58 am" src="https://user-images.githubusercontent.com/3696230/29498622-02b79a4c-8609-11e7-9cfa-ccd8dc63843f.png">

**Comment by cuzv** [comment]
Thanks for your report, it has been fixed in 43db771;
